### ISSUE TITLE
vs activity error

### ISSUE THREAD

**Issue by a44281071** [mike-ward/VSColorOutput#18] opened 2016-01-22 01:34 UTC
I'm using vs2015 update1.
There is an error Message:
``` xml
  <entry>
    <record>810</record>
    <time>2016/01/22 01:27:10.305</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: &#x504F;&#x79FB;&#x91CF;&#x548C;&#x957F;&#x5EA6;&#x8D85;&#x51FA;&#x6570;&#x7EC4;&#x7684;&#x754C;&#x9650;&#xFF0C;&#x6216;&#x8005;&#x8BA1;&#x6570;&#x5927;&#x4E8E;&#x4ECE;&#x7D22;&#x5F15;&#x5230;&#x6E90;&#x96C6;&#x5408;&#x7ED3;&#x5C3E;&#x5904;&#x7684;&#x5143;&#x7D20;&#x6570;&#x91CF;&#x3002;&#x000D;&#x000A;   &#x5728; System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)&#x000D;&#x000A;   &#x5728; System.Collections.Generic.List`1.RemoveRange(Int32 index, Int32 count)&#x000D;&#x000A;   &#x5728; VSColorOutput.Output.TimeStamp.TimeStampMargin.TextBufferOnChanged(Object sender, TextContentChangedEventArgs ea)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>
```
What's the problem with it？Thanks!

**Comment by mike-ward** [comment] 2016-01-22 02:15
Duplicate of #17

**Closed by mike-ward** 2016-01-22 02:15 UTC
