### ISSUE TITLE
Live Unit Testing results are categorised red even when all passed

### ISSUE THREAD

**Issue by simonsabin** [mike-ward/VSColorOutput#74] opened 2018-05-22 15:15 UTC
Live unit testing outputs a summary as the following which is being categorised red when it should only be red if tests failed
`[15:56:51.735 Info] Finished executing tests. (Passed: 6, Failed: 0, Skipped: 0, Not Executed: 0)`
Suggest a regex like the following and categorise as BuildHead
`Finished executing tests.*Failed\: 0`

**Comment by JakobFerdinand** [comment] 2018-07-26 05:06
Duplicate of #72

**Closed** 2020-02-24 18:34 UTC
